tracking_frame: "laser_frame"
published_frame: "base_link"
odom_frame: "odom"
map_frame: "map"

provide_odom_frame: true
publish_frame_projected_to_2d: true
use_odometry: false
use_nav_sat: false
use_landmarks: false

num_laser_scans: 1
num_multi_echo_laser_scans: 0
num_point_clouds: 0

lookup_transform_timeout_sec: 0.2
submap_publish_period_sec: 0.5
pose_publish_period_sec: 5e-3
trajectory_publish_period_sec: 30e-3
